add_compile_definitions(_DEFAULT_SOURCE)
# Horizon rejects write+execute on one address. Oaknut's allocator is patched
# to a libnx JIT alias before this target is compiled.
execute_process(
  COMMAND bash "${CMAKE_CURRENT_LIST_DIR}/../patch-dynarmic-jit.sh" "${CMAKE_SOURCE_DIR}"
  RESULT_VARIABLE _zeebx_jit_patch
)
if(NOT _zeebx_jit_patch EQUAL 0)
  message(FATAL_ERROR "Switch JIT patch failed (${_zeebx_jit_patch})")
endif()
add_compile_definitions(ZEEBX_SWITCH_JIT)
# newlib has no sys/mman.h. Oaknut's code allocator includes it.
include_directories(BEFORE SYSTEM "${CMAKE_CURRENT_LIST_DIR}/../compat")

# Horizon has no POSIX signals or ucontext. Dynarmic records the Linux handler
# before this file's directory has finished, so replace it once the target exists.
function(_zeebx_generic_exception_handler)
  if(NOT TARGET dynarmic)
    return()
  endif()
  get_target_property(_srcs dynarmic SOURCES)
  set(_out "")
  set(_replaced FALSE)
  foreach(_src IN LISTS _srcs)
    if(_src MATCHES "exception_handler_posix\\.cpp$")
      get_filename_component(_dir "${_src}" DIRECTORY)
      if(_dir STREQUAL "" OR _dir STREQUAL ".")
        list(APPEND _out "exception_handler_generic.cpp")
      else()
        list(APPEND _out "${_dir}/exception_handler_generic.cpp")
      endif()
      set(_replaced TRUE)
    else()
      list(APPEND _out "${_src}")
    endif()
  endforeach()
  if(_replaced)
    set_property(TARGET dynarmic PROPERTY SOURCES ${_out})
    message(STATUS "Switch build: dynarmic uses the generic exception handler")
  endif()
  foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(_libs dynarmic ${_prop})
    if(_libs MATCHES "-NOTFOUND$")
      continue()
    endif()
    set(_kept "")
    foreach(_lib IN LISTS _libs)
      if(NOT _lib MATCHES "(^|:)rt>?$")
        list(APPEND _kept "${_lib}")
      endif()
    endforeach()
    set_property(TARGET dynarmic PROPERTY ${_prop} "${_kept}")
  endforeach()
endfunction()
cmake_language(DEFER CALL _zeebx_generic_exception_handler)
